#include "Framework.h"
#include "Gamemode.h"

DWORD Main(LPVOID)
{
    AllocConsole();
    FILE* streamPtr;
    freopen_s(&streamPtr, "CONOUT$", "w", stdout);
    SetConsoleTitleA(("Titanium v" + Globals::GameserverVersion).c_str());

    Sleep(1000);

    LOG("Initializing Gameserver...\n");

    Sleep(1500);

    LOG("Made By @therealptah");

    Sleep(1500);

    LOG("SDK Generated By Dumper-7\n");

    Sleep(1000);

    MH_Initialize();
    InitGObjects();

    Sleep(5000);

    ((UKismetSystemLibrary*)UKismetSystemLibrary::StaticClass()->DefaultObject)->ExecuteConsoleCommand(Helpers::GetWorld(), L"open Athena_Terrain", nullptr);
    UObject::FindObject<UFortEngine>("FortEngine_")->GameInstance->LocalPlayers.Remove(0);

    MH_CreateHook((LPVOID)Helpers::GetOffset(0x29CE460), Network::TickFlushHook, (void**)&Network::TickFlush);
    MH_EnableHook((LPVOID)Helpers::GetOffset(0x29CE460));

    MH_CreateHook((LPVOID)Helpers::GetOffset(0x124A9B0), Network::KickPlayer, nullptr);
    MH_EnableHook((LPVOID)Helpers::GetOffset(0x124A9B0));

    MH_CreateHook((LPVOID)Helpers::GetOffset(0x1251DA0), Network::ValidationFailure, nullptr);
    MH_EnableHook((LPVOID)Helpers::GetOffset(0x1251DA0));

    MH_CreateHook((LPVOID)Helpers::GetOffset(0x125B070), Network::NoReservation, nullptr);
    MH_EnableHook((LPVOID)Helpers::GetOffset(0x125B070));

    return 1;
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    {
        CreateThread(0, 0, Main, 0, 0, 0);
        break;
    }
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}